blog/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

import homepage.views as home_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home_views.index, name="home"),
    path("blog/", include("blog_app.urls")),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="homepage/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="homepage/logout.html"),
        name="logout",
    ),
    path("register/", home_views.register, name="register"),
]

blog_app/urls.py
from django.urls import include, path

from .views import *

app_name = "blog_app"
urlpatterns = [
    path("", index_view, name="index"),
    path("create/", create_post_view, name="create_post"),
    path("edit/<int:post_id>/", edit_post_view, name="edit_post"),
    path("<int:post_id>/", post_view, name="post_detail"),
]

blog_app/models.py
from django.conf import settings
from django.db import models

# Create your models here.

USER_MODEL = settings.AUTH_USER_MODEL


class Post(models.Model):
    author = models.ForeignKey(
        USER_MODEL, verbose_name="Autor", on_delete=models.CASCADE
    )
    creation_date = models.DateTimeField("Erstellungsdatum", auto_now_add=True)
    edit_date = models.DateTimeField("Bearbeitungsdatum", auto_now=True)
    text = models.CharField("Text", max_length=1024)
    title = models.CharField("Titel", max_length=255)

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post, verbose_name="Post", on_delete=models.CASCADE, related_name="comments"
    )
    author = models.ForeignKey(
        USER_MODEL, verbose_name="Autor", on_delete=models.CASCADE
    )
    creation_date = models.DateTimeField("Erstellungsdatum", auto_now_add=True)
    text = models.CharField("Text", max_length=512)

    class Meta:
        verbose_name = "Kommentar"
        verbose_name_plural = "Kommentare"

    def __str__(self):
        return self.text[:50]

homepage/models.py
from django.db import models

# Create your models here.

blog_app/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "text"]
        widgets = {"text": forms.Textarea()}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]

blog_app/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render

from .forms import CommentForm, PostForm
from .models import Post

# Create your views here.


def index_view(request: HttpRequest) -> HttpResponse:
    posts = Post.objects.all()
    context = {
        "posts": posts,
    }
    return render(request, "blog_app/index.html", context)


@login_required
def create_post_view(request: HttpRequest) -> HttpResponse:
    form = PostForm()
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post: Post = form.save(commit=False)
            post.author = request.user
            post.save()

    return render(request, "blog_app/create_post.html", {"form": form})


@login_required
def edit_post_view(request: HttpRequest, post_id: int) -> HttpResponse:
    post = Post.objects.get(id=post_id)
    if post.author != request.user:
        return HttpResponse("Unauthorized", status=401)

    form = PostForm(instance=post)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, "Post erfolgreich bearbeitet!")
            return redirect("blog_app:post_detail", post_id=post.id)

    return render(request, "blog_app/edit_post.html", {"form": form})


def post_view(request: HttpRequest, post_id: int) -> HttpResponse:
    post = Post.objects.get(id=post_id)
    if not request.user.is_authenticated:
        comment_form = None
    else:
        comment_form = CommentForm()
        if request.method == "POST":
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.author = request.user
                comment.post = post
                comment.save()

    context = {
        "post": post,
        "comment_form": comment_form,
        "is_creator": post.author == request.user,
    }
    return render(request, "blog_app/post.html", context)

homepage/views.py
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.views.decorators.debug import sensitive_post_parameters

# Create your views here.


def index(request: HttpRequest) -> HttpResponse:
    return render(
        request,
        "homepage/index.html",
    )


@sensitive_post_parameters()
def register(request: HttpRequest):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get("username")

            messages.success(request, f"Account für {username} erstellt!")
            return redirect("login")
    else:
        form = UserCreationForm()
    context = {"form": form}
    return render(request, "homepage/register.html", context)

blog_app/templates/blog_app/create_post.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block title %}
    OFahrt Blog
{% endblock title %}
{% block brand %}
    OFahrt Blog
{% endblock brand %}
{% block content %}
    <h1>Neuen Beitrag erstellen</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Erstellen</button>
    </form>
{% endblock content %}

blog_app/templates/blog_app/edit_post.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block title %}
    OFahrt Blog
{% endblock title %}
{% block brand %}
    OFahrt Blog
{% endblock brand %}
{% block content %}
    <h1>Beitrag bearbeiten</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Speichern</button>
    </form>
{% endblock content %}

blog_app/templates/blog_app/include/comment_creation.html
{% load crispy_forms_filters %}
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Kommentieren</button>
</form>

blog_app/templates/blog_app/include/post.html
<div class="card">
    <div class="card-body">
        <h4 class="card-title">{{ post.title }}</h4>
        <p class="card-text">{{ post.text|truncatechars_html:25|linebreaks }}</p>
        <a href="{% url "blog_app:post_detail" post.id %}"
           class="btn btn-primary">Anschauen</a>
    </div>
</div>

blog_app/templates/blog_app/index.html
{% extends "base.html" %}
{% block title %}
    OFahrt Blog
{% endblock title %}
{% block brand %}
    OFahrt Blog
{% endblock brand %}
{% block content %}
    <h1>Willkommen zum Blog auf der OFahrt 2025</h1>
    <p>Hier befinden sich alle Blog Beiträge.</p>
    {% if user.is_authenticated %}
        <a href="{% url "blog_app:create_post" %}">Neuen Post erstellen</a>
    {% endif %}
    <hr>
    <div class="row row-cols-4 gy-4">
        {% for post in posts %}
            <div class="col">{% include "blog_app/include/post.html" with post=post %}</div>
        {% endfor %}
    </div>
{% endblock content %}

blog_app/templates/blog_app/post.html
{% extends "base.html" %}
{% block title %}
    OFahrt Blog
{% endblock title %}
{% block brand %}
    OFahrt Blog
{% endblock brand %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p>
        {% if is_creator %}
            <a href="{% url "blog_app:edit_post" post.id %}">Bearbeiten</a>
        {% endif %}
        <ul>
            <li>Autor: {{ post.author }}</li>
            <li>Erstellt am: {{ post.creation_date|date:"d.m.Y H:i" }}</li>
            <li>Aktualisiert am: {{ post.edit_date|date:"d.m.Y H:i" }}</li>
        </ul>
    </p>
    <p>{{ post.text|linebreaks }}</p>
    <hr>
    {% if comment_form %}
        <div class="mb-3">{% include "blog_app/include/comment_creation.html" with form=comment_form %}</div>
        <hr>
    {% endif %}
    <h2>Kommentare</h2>
    <ul>
        {% for comment in post.comments.all %}
            <li>
                <strong>{{ comment.author.username }}</strong> schreibt:
                {{ comment.text }}
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

homepage/templates/homepage/index.html
{% extends "base.html" %}
{% block title %}
    OFahrt 2025 Webdev Workshop
{% endblock title %}
{% block brand %}
    OFahrt 2025
{% endblock brand %}
{% block content %}
    <h1>YAY es funktioniert</h1>
{% endblock content %}

homepage/templates/homepage/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Anmelden
{% endblock title %}
{% block brand %}
    Anmelden
{% endblock brand %}
{% block nav_item %}
    {{ block.super }}
    <a class="nav-link" href="{% url 'register' %}">Registrieren</a>
{% endblock nav_item %}
{% block alerts %}
    {% if next %}
        {% if user.is_authenticated %}
            <div class="alert alert-warning">
                Du hast keinen Zugriff auf diese Seite. Bitte logge dich mit einem anderen Account ein.
            </div>
        {% else %}
            <div class="alert alert-danger">Bitte logge dich ein um diese Seite zu sehen.</div>
        {% endif %}
    {% endif %}
{% endblock alerts %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <legend class="card-header">Bitte Melde dich an</legend>
        <div class="card-body">
            <fieldset class="mb-3">
                {{ form|crispy }}
            </fieldset>
            <div>
                <button class="btn btn-info" type="submit">Anmelden</button>
            </div>
        </div>
    </form>
    <div class="d-flex border-top card-footer">
        <small class="text-body-secondary">
            Du hast noch keinen Account? <a href="{% url 'register' %}">Registrieren</a>
        </small>
    </div>
{% endblock content %}

homepage/templates/homepage/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Registrieren
{% endblock title %}
{% block brand %}
    Registrieren
{% endblock brand %}
{% block nav_item %}
    {{ block.super }}
    <a class="nav-link" href="{% url 'login' %}">Anmelden</a>
{% endblock nav_item %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <fieldset>
            <legend class="border-bottom card-header">Registrieren</legend>
            <div class="card-body">
                {{ form|crispy }}
                <button class="btn btn-outline-info" type="submit">Registrieren</button>
            </div>
        </fieldset>
    </form>
    <div class="border-top card-footer">
        <small class="text-body-secondary">
            Du hast schon einen Account? <a href="{% url 'login' %}">Anmelden</a>
        </small>
    </div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="de" prefix="og: http://ogp.me/ns#">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block meta %}
        {% endblock meta %}
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}?v=5.3.3">
        <link rel="stylesheet" href="{% static 'css/bootstrap-icons.min.css' %}">
        {% block stylesheet %}
        {% endblock stylesheet %}
        <title>
            {% block title %}
                OFahrt 2025 Webdev Workshop
            {% endblock title %}
        </title>
    </head>
    <body class="d-flex flex-column min-vh-100
                 {% block body_classes %}
                     bg-body-tertiary
                 {% endblock body_classes %}"
          {% block body_extra_context %}
          {% endblock body_extra_context %}
          data-bs-theme="dark">
        <header class="sticky-top">
            <nav class="navbar navbar-expand-sm shadow-sm bg-primary"
                 data-bs-theme="dark">
                <div class="container-xl">
                    <a class="navbar-brand mb-0 h1 text-wrap"
                       href="{% block brand_url %}{% url 'home' %}{% endblock brand_url %}">
                        {% block brand %}
                            OFahrt 2025
                        {% endblock brand %}
                    </a>
                    <button class="navbar-toggler"
                            type="button"
                            data-bs-toggle="offcanvas"
                            data-bs-target="#navbarNav"
                            aria-controls="navbarNav"
                            aria-expanded="false"
                            aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="offcanvas offcanvas-start"
                         tabindex="-1"
                         id="navbarNav"
                         aria-labelledby="offcanvasTitle">
                        <div class="offcanvas-header">
                            <h5 class="offcanvas-title" id="offcanvasTitle">Navigation</h5>
                            <button type="button"
                                    class="btn-close"
                                    data-bs-dismiss="offcanvas"
                                    aria-label="Close"></button>
                        </div>
                        <div class="offcanvas-body">
                            <div class="ms-auto navbar-nav nav-underline">
                                {% block nav_item %}
                                {% endblock nav_item %}
                                <a href="{% url "blog_app:index" %}" class="nav-link">Posts</a>
                                {% if user.is_authenticated %}
                                    <a href="{% url 'logout' %}" class="nav-link">
                                        <i class="bi bi-box-arrow-right"></i> Abmelden
                                    </a>
                                {% else %}
                                    <a href="{% url 'login' %}" class="nav-link"><i class="bi bi-box-arrow-in-right"></i> Anmelden</a>
                                {% endif %}
                                {% if user.is_superuser %}
                                    <a class="nav-link"
                                       href="{% url 'admin:index' %}"
                                       aria-label="Admin Panel">
                                        <i class="bi bi-shield-shaded"></i> Admin Panel
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <main class="d-flex flex-column flex-fill" role="main">
            {% if messages %}
                <div class="container-xl">
                    {% for message in messages %}
                        <div class="my-2 alert alert-{{ message.tags }} alert-dismissible fade show"
                             role="alert">
                            {{ message }}
                            <button type="button"
                                    class="btn-close"
                                    data-bs-dismiss="alert"
                                    aria-label="Close"></button>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="d-flex flex-column container-xl flex-fill">
                <div class="shadow bg-body p-3">
                    {% block pre_content %}
                    {% endblock pre_content %}
                    {% block content %}
                    {% endblock content %}
                    {% block post_content %}
                    {% endblock post_content %}
                </div>
            </div>
        </main>
        <footer class="footer bg-body-secondary">
            <div class="container-xl">
                <div class="py-3 border-top text-body-secondary d-flex justify-content-between align-items-center flex-wrap">
                    <span class="col-sm-3 text-reset d-flex justify-content-center">
                        <a href="https://github.com/Atlasfreak/" class="text-reset">Source Code</a>
                    </span>
                </div>
            </div>
        </footer>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}?v=5.3.3"></script>
        {% block javascript %}
        {% endblock javascript %}
    </body>
</html>